### ISSUE TITLE
提供初始化控制

### ISSUE THREAD

**Issue by hxzAugustinus** [OpenInstall/openinstall-react-native#11]
能不能优化一下，不立即初始化，导出一个初始化的函数：
原生接入可以包含以下逻辑：
App 启动时，调用OpenInstall.init(context)方法完成 sdk 初始化 ，务必确保用户同意《隐私政策》之后，再初始化openinstall SDK；如果用户不同意，则不进行openinstall SDK初始化

而本库现在自动初始化，不管是否已同意 ，无法和隐私协议 的 ‘同意’   进行顺序控制 。

**Comment by hxzAugustinus** [comment]
@WuWenhui  @loadingCooper

**Comment by wenkiwu** [comment]
谢谢您的反馈，我们会尽快解决。

**Comment by wenkiwu** [comment]
新版本已经发布，请参考最新的文档集成。
有任何问题或建议请联系我们

**Comment by hxzAugustinus** [comment]
好的
