### ISSUE TITLE
build.gradle 需要修正

### ISSUE THREAD

**Issue by hcygit** [OpenInstall/openinstall-react-native#7]
在 android/build.gradle 內
應該用一個function去設定android{}區塊內的版本

例如
def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}
compileSdkVersion safeExtGet('compileSdkVersion', 28)
...

否則將會影響到使用者原本專案的設定而在build時產生error

昨天在QQ群裡面反映過了
請協助修正謝謝

**Comment by wenkiwu** [comment]
谢谢指出！ 已修正
